### ISSUE TITLE
Support to SSL connection

### ISSUE THREAD

**Issue by psyking841** [IBM/presto-db2#14]
Current version of db2 presto plugin does not support SSL connection.

Updated on June 17, 2019, 2:14PM:
Here is the settings I had for the plugin. To enable the ssl, I used the url with sslConnection set to true.
```
connector.name=db2
connection-url=jdbc:db2://db2whoc-flex-performance-riubnzs.services.dal.bluemix.net:50001/BLUDB:sslConnection=true
connection-user=myuser
connection-password=mypassword
```

And here is the error when I am running queries from Presto to access DB2 table:
```
java.sql.SQLException: Query failed (#20190617_180905_00000_jas3k): [jcc][10165][10051][4.25.13] Invalid database URL syntax: jdbc:db2://db2whoc-flex-performance-riubnzs.services.dal.bluemix.net:50001/BLUDB:sslConnection=true. ERRORCODE=-4461, SQLSTATE=42815
	at io.prestosql.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1839)
	at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1749)
	at io.prestosql.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:118)
	at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:251)
	at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:229)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.executeSql(JDBCInterpreter.java:748)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.interpret(JDBCInterpreter.java:831)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:103)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:632)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:188)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.prestosql.spi.PrestoException: [jcc][10165][10051][4.25.13] Invalid database URL syntax: jdbc:db2://db2whoc-flex-performance-riubnzs.services.dal.bluemix.net:50001/BLUDB:sslConnection=true. ERRORCODE=-4461, SQLSTATE=42815
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:132)
	at io.prestosql.plugin.jdbc.JdbcClient.schemaExists(JdbcClient.java:34)
	at io.prestosql.plugin.jdbc.JdbcMetadata.schemaExists(JdbcMetadata.java:67)
	at io.prestosql.metadata.MetadataManager.lambda$schemaExists$0(MetadataManager.java:290)
```

So it seems the plugin does not recognize the sslConnection option appended to the end of URL.

**Comment by psyking841** [comment]
PR has been filed for this issue: https://github.com/IBM/presto-db2/pull/15

**Comment by shawnzhu** [comment]
In one case, I used this library connected to DashDB (named _DB2 on Cloud_ now) via SSL and it works well w/o code change. So I assume one of the expected outcome is documentation on howto.

**Comment by psyking841** [comment]
I would love to know how to connect to learn the "how to".
I am using "IBM Db2 Warehouse on Cloud", at lease for this product, appending "sslConnection=true" to the url did not work for my case.

**Comment by psyking841** [comment]
This ticket is not for enhancement, it is a bug report... @shawnzhu

**Comment by shawnzhu** [comment]
The error message from https://github.com/IBM/presto-db2/issues/14#issue-456956482 is `Invalid database URL syntax: jdbc:db2://db2whoc-flex-performance-riubnzs.services.dal.bluemix.net:50001/BLUDB:sslConnection=true. ERRORCODE=-4461, SQLSTATE=42815`

So what doesn't work:

```
jdbc:db2://xxx.services.dal.bluemix.net:50001/BLUDB:sslConnection=true
```

What works (for me):

```
jdbc:db2://xxx.services.dal.bluemix.net:50001/BLUDB:sslConnection=true;
```

So the difference is the trailing semi-colon. See official guide in https://www.ibm.com/support/knowledgecenter/en/SS6NHC/com.ibm.swg.im.dashdb.doc/connecting/connect_connecting_jdbc_applications.html

**Comment by psyking841** [comment]
@shawnzhu 
Yeah, you are right. I just tested the URL with colon. And it works. Thanks to IBM's innovative URL design for their DB2 jdbc driver!

**Comment by psyking841** [comment]
Let me know if you would like me to close the PR: https://github.com/IBM/presto-db2/pull/15.

**Comment by shawnzhu** [comment]
> Yeah, you are right. I just tested the URL with colon. And it works. Thanks to IBM's innovative URL design for their DB2 jdbc driver!

@psyking841 I prefer not to change what it was in DB2 JDBC driver/doc when using this connector, or we can do something to make such configuration more humane. will close #15 but create a new one to highlight this case.
