### ISSUE TITLE
Supports renaming table

### ISSUE THREAD

**Issue by shawnzhu** [IBM/presto-db2#28]
## What happened

When using [`CREATE TABLE AS`](https://prestosql.io/docs/325/sql/create-table-as.html), it throws SQL Error when target table contains column in int type:

```SQL
CREATE TABLE IF NOT EXISTS bludb.xxx.summary_table_1
COMMENT 'summary table for test'
AS
SELECT
    CAST(total_members AS INT) AS total_members
FROM hive.default.fact_table_1
WHERE dt = '2020-02-02'
```

It will throw this error message when running ☝️SQL via prestosql:

```
Query 20200204_020247_00008_8ks7p failed: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=ALTER TABLE HCW88054.TMP_PRESTO_7;BEGIN-OF-STATEMENT;<rename_stogroup>, DRIVER=4.25.13
```

## Expectation

It should create a new table `summary_table_1` with data from ☝️ query from the Hive table `fact_table_1`.

**Comment by shawnzhu** [comment]
More information found from query details:

stacktrace:

```
io.prestosql.spi.PrestoException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=ALTER TABLE HCW88054.TMP_PRESTO_7;BEGIN-OF-STATEMENT;<rename_stogroup>, DRIVER=4.25.13
	at io.prestosql.plugin.jdbc.BaseJdbcClient.renameTable(BaseJdbcClient.java:523)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.commitCreateTable(BaseJdbcClient.java:493)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$commitCreateTable$17(StatisticsAwareJdbcClient.java:180)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:47)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.commitCreateTable(StatisticsAwareJdbcClient.java:180)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.commitCreateTable(ForwardingJdbcClient.java:116)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.commitCreateTable(ForwardingJdbcClient.java:116)
	at io.prestosql.plugin.jdbc.JdbcMetadata.finishCreateTable(JdbcMetadata.java:226)
	at io.prestosql.metadata.MetadataManager.finishCreateTable(MetadataManager.java:771)
	at io.prestosql.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:2852)
	at io.prestosql.operator.TableFinishOperator.getOutput(TableFinishOperator.java:297)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_325____20200204_013357_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=ALTER TABLE HCW88054.TMP_PRESTO_7;BEGIN-OF-STATEMENT;<rename_stogroup>, DRIVER=4.25.13
	at com.ibm.db2.jcc.am.b6.a(b6.java:810)
	at com.ibm.db2.jcc.am.b6.a(b6.java:66)
	at com.ibm.db2.jcc.am.b6.a(b6.java:140)
	at com.ibm.db2.jcc.am.k3.c(k3.java:2824)
	at com.ibm.db2.jcc.am.k3.d(k3.java:2808)
	at com.ibm.db2.jcc.am.k3.b(k3.java:2168)
	at com.ibm.db2.jcc.t4.ab.k(ab.java:446)
	at com.ibm.db2.jcc.t4.ab.c(ab.java:104)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.av.h(av.java:124)
	at com.ibm.db2.jcc.am.k3.ak(k3.java:2163)
	at com.ibm.db2.jcc.am.k3.a(k3.java:3366)
	at com.ibm.db2.jcc.am.k3.e(k3.java:1131)
	at com.ibm.db2.jcc.am.k3.execute(k3.java:1110)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:779)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.renameTable(BaseJdbcClient.java:520)
	... 21 more
```

**Comment by shawnzhu** [comment]
So the key error message is `com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=ALTER TABLE HCW88054.TMP_PRESTO_7;BEGIN-OF-STATEMENT;<rename_stogroup>, DRIVER=4.25.13` which is a SQL syntax error.

The problem is it uses `io.prestosql.plugin.jdbc.BaseJdbcClient.renameTable(BaseJdbcClient.java:520)` which translate naming table to SQL `"ALTER TABLE %s RENAME TO %s"`, which is not supported db2 SQL. Instead, it shall translate to SQL `"RENAME TABLE %s TO %s;"`. see https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/sqlref/src/tpc/db2z_sql_rename.html
